services:
  haydaramru-com:
    image: haydaramru/haydaramru.com:latest
    restart: unless-stopped
    ports:
      - "2602:2602"
    volumes:
      - ./ssl:/etc/ssl/cloudflare:ro
    environment:
      - NODE_ENV=production
